name = "bloxlibs/betterscale"
version = "2.1.0"
description = "A UI scaling solution for Roblox, without the headache."
authors = ["PcoiDev"]
repository = "https://github.com/bloxlibs/BetterScale"
license = "BloxLibs"
includes = ["src/*", "README.md", "pesde.toml", "LICENSE", "index.d.ts"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
