[package]
name = "pcoidev/betterscale"
version = "2.1.0"
description = "A UI scaling solution for Roblox, without the headache."
license = "BloxLibs"
authors = ["PcoiDev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
